DELETE FROM retete;

INSERT INTO retete (nume, descriere, imagine, categorie, subcategorie, mod_categorizare, pret, timp_preparare, portii, data_adaugare, complexitate, ingrediente, echipamente, este_rapida, aprecieri, instructiuni) VALUES
('Ciorba de burta', 'Ciorba traditionala romaneasca, gustoasa si satioasa.', 'Resurse/images/12387.jpg', 'Feluri principale', 'Romaneasca', 'Dupa tipul de carne: vita', 25, 60, 4, '2024-06-28', 'Mediu', ARRAY['burta de vita', 'oua', 'smantana', 'usturoi', 'otet'], ARRAY['oala', 'lingura', 'cutit'], false, 120, '1. Fierbe carnea... 2. Adauga legumele... 3. Serveste cu smantana.'),
('Tiramisu', 'Desert italian clasic cu mascarpone si cafea.', 'Resurse/images/14508.jpg', 'Deserturi', 'Italiana', 'Fara coacere', 18, 30, 6, '2024-06-28', 'Usor', ARRAY['mascarpone', 'cafea', 'piscoturi', 'cacao'], ARRAY['castron', 'tel', 'tava'], true, 200, '1. Amesteca mascarpone... 2. Inmoaie piscoturile... 3. Monteaza straturile.'),
('Sushi', 'Rulouri japoneze cu orez si peste.', 'Resurse/images/19956.jpg', 'Feluri principale', 'Japoneza', 'Dupa tipul de peste', 40, 50, 2, '2024-06-28', 'Dificil', ARRAY['orez', 'alge nori', 'somon', 'avocado'], ARRAY['covoras bambus', 'cutit'], false, 150, '1. Fierbe orezul... 2. Ruleaza ingredientele... 3. Taie si serveste.'),
('Salata Caesar', 'Salata clasica cu pui si dressing Caesar.', 'Resurse/images/pexels-ash-craig-122861-376464.jpg', 'Aperitive', 'Internationala', 'Dupa tipul de carne: pui', 22, 20, 2, '2024-06-28', 'Usor', ARRAY['salata', 'piept de pui', 'parmezan', 'crutoane'], ARRAY['bol', 'tigaie'], true, 90, '1. Prajeste puiul... 2. Amesteca ingredientele... 3. Adauga dressing.'),
('Papanasi', 'Desert romanesc cu branza si smantana.', 'Resurse/images/pexels-ella-olsson-572949-1640772.jpg', 'Deserturi', 'Romaneasca', 'Dupa tipul de branza', 15, 35, 4, '2024-06-28', 'Mediu', ARRAY['branza de vaci', 'oua', 'faina', 'smantana', 'dulceata'], ARRAY['castron', 'tigaie'], false, 110, '1. Amesteca ingredientele... 2. Prajeste papanasii... 3. Serveste cu smantana si dulceata.'),
('Pizza Margherita', 'Pizza italiana cu sos de rosii si mozzarella.', 'Resurse/images/pexels-ella-olsson-572949-1640777.jpg', 'Feluri principale', 'Italiana', 'Dupa tipul de blat', 28, 25, 2, '2024-06-28', 'Usor', ARRAY['faina', 'sos de rosii', 'mozzarella', 'busuioc'], ARRAY['cuptor', 'tava'], true, 180, '1. Pregateste aluatul... 2. Adauga toppingurile... 3. Coace la cuptor.'),
('Sarmale', 'Sarmale traditionale in foi de varza.', 'Resurse/images/pexels-fotios-photos-1279330.jpg', 'Feluri principale', 'Romaneasca', 'Dupa tipul de carne: porc', 35, 120, 6, '2024-06-28', 'Dificil', ARRAY['carne tocata', 'varza murata', 'orez', 'ceapa'], ARRAY['oala', 'lingura'], false, 210, '1. Amesteca ingredientele... 2. Ruleaza sarmalele... 3. Fierbe-le.'),
('Guacamole', 'Pasta mexicana de avocado.', 'Resurse/images/pexels-janetrangdoan-1099680.jpg', 'Aperitive', 'Mexicana', 'Fara coacere', 12, 10, 3, '2024-06-28', 'Usor', ARRAY['avocado', 'ceapa', 'rosii', 'lime'], ARRAY['furculita', 'castron'], true, 75, '1. Paseaza avocado... 2. Amesteca ingredientele... 3. Serveste cu chipsuri.'),
('Clatite', 'Clatite pufoase cu gem.', 'Resurse/images/12387(1).jpg', 'Deserturi', 'Internationala', 'Dupa umplutura', 10, 20, 4, '2024-06-28', 'Usor', ARRAY['faina', 'oua', 'lapte', 'gem'], ARRAY['tigaie', 'polonic'], true, 130, '1. Amesteca ingredientele... 2. Prajeste clatitele... 3. Umple cu gem.'),
('Paella', 'Preparat spaniol cu orez si fructe de mare.', 'Resurse/images/12387(2).jpg', 'Feluri principale', 'Spaniola', 'Dupa tipul de carne: fructe de mare', 38, 45, 4, '2024-06-28', 'Mediu', ARRAY['orez', 'creveti', 'midii', 'mazare'], ARRAY['tigaie', 'lingura'], false, 95, '1. Prajeste ingredientele... 2. Fierbe orezul... 3. Amesteca si serveste.'),
('Cheesecake', 'Desert cremos cu branza si blat crocant.', 'Resurse/images/14508(1).jpg', 'Deserturi', 'Americana', 'Fara coacere', 20, 50, 8, '2024-06-28', 'Mediu', ARRAY['branza crema', 'biscuiti', 'unt', 'zahar'], ARRAY['tava', 'castron'], false, 160, '1. Pregateste blatul... 2. Amesteca crema... 3. Lasa la rece.'),
('Shakshuka', 'Oua posate in sos de rosii picant.', 'Resurse/images/19956(1).jpg', 'Feluri principale', 'Orientala', 'Dupa tipul de legume', 16, 25, 2, '2024-06-28', 'Usor', ARRAY['oua', 'rosii', 'ardei', 'ceapa'], ARRAY['tigaie', 'lingura'], true, 85, '1. Prajeste legumele... 2. Adauga ouale... 3. Gateste la foc mic.'),
('Mousse au chocolat', 'Desert frantuzesc cu ciocolata.', 'Resurse/images/19956(2).jpg', 'Deserturi', 'Franceza', 'Fara coacere', 22, 15, 4, '2024-06-28', 'Usor', ARRAY['ciocolata', 'oua', 'frisca'], ARRAY['castron', 'tel'], true, 140, '1. Topeste ciocolata... 2. Amesteca cu ouale... 3. Lasa la rece.'),
('Burger vegetarian', 'Burger cu chiftea de legume.', 'Resurse/images/14508(2).jpg', 'Feluri principale', 'Internationala', 'Dupa tipul de chiftea', 27, 30, 2, '2024-06-28', 'Mediu', ARRAY['chiftea vegetala', 'chifla', 'salata', 'rosii'], ARRAY['tigaie', 'cutit'], true, 100, '1. Prajeste chifteaua... 2. Monteaza burgerul... 3. Serveste.'),
('Supa crema de dovleac', 'Supa fina de dovleac cu smantana.', 'Resurse/images/pexels-ella-olsson-572949-1640772.jpg', 'Aperitive', 'Internationala', 'Dupa tipul de legume', 14, 40, 3, '2024-06-28', 'Usor', ARRAY['dovleac', 'smantana', 'ceapa', 'usturoi'], ARRAY['oala', 'blender'], false, 70, '1. Fierbe dovleacul... 2. Paseaza... 3. Adauga smantana.'),
('Lasagna', 'Paste italiene la cuptor cu sos ragu.', 'Resurse/images/pexels-janetrangdoan-1099680.jpg', 'Feluri principale', 'Italiana', 'Dupa tipul de carne: vita', 32, 90, 6, '2024-06-28', 'Dificil', ARRAY['foi lasagna', 'carne tocata', 'sos rosii', 'parmezan'], ARRAY['cuptor', 'tava'], false, 175, '1. Pregateste sosul... 2. Monteaza straturile... 3. Coace la cuptor.'),
('Brownie', 'Prajitura americana cu ciocolata.', 'Resurse/images/pexels-fotios-photos-1279330.jpg', 'Deserturi', 'Americana', 'Dupa tipul de ciocolata', 13, 35, 8, '2024-06-28', 'Usor', ARRAY['ciocolata', 'faina', 'oua', 'zahar'], ARRAY['tava', 'cuptor'], false, 155, '1. Amesteca ingredientele... 2. Coace la cuptor... 3. Taie si serveste.'),
('Falafel', 'Chiftelute orientale din naut.', 'Resurse/images/pexels-ella-olsson-572949-1640777.jpg', 'Aperitive', 'Orientala', 'Dupa tipul de leguminoase', 11, 25, 4, '2024-06-28', 'Usor', ARRAY['naut', 'ceapa', 'patrunjel', 'condimente'], ARRAY['robot bucatarie', 'tigaie'], true, 80, '1. Paseaza nautul... 2. Formeaza chiftelutele... 3. Prajeste.'),
('Ratatouille', 'Tocana frantuzeasca de legume.', 'Resurse/images/12387.jpg', 'Feluri principale', 'Franceza', 'Dupa tipul de legume', 19, 50, 3, '2024-06-28', 'Mediu', ARRAY['vinete', 'dovlecei', 'ardei', 'rosii'], ARRAY['tigaie', 'cutit'], false, 90, '1. Taie legumele... 2. Prajeste... 3. Gateste la foc mic.'),
('Pavlova', 'Desert cu bezea si fructe.', 'Resurse/images/14508.jpg', 'Deserturi', 'Australiana', 'Dupa tipul de fructe', 24, 120, 8, '2024-06-28', 'Dificil', ARRAY['albusuri', 'zahar', 'frisca', 'fructe'], ARRAY['mixter', 'tava'], false, 105, '1. Bate albusurile... 2. Coace bezeaua... 3. Decoreaza cu fructe.');